In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
type(a1)

numpy.ndarray

In [4]:

a1.ndim

1

In [6]:
a1.shape

(4,)

In [7]:

b = [4.5, 5.1, 6.2]
type(b)

list

In [8]:

b1 = np.array(b)
b1

array([4.5, 5.1, 6.2])

In [9]:
type(b1)

numpy.ndarray

In [10]:
c = [[1, 2, 3, 4],
     [5, 6, 7, 8]]
type(c)

list

In [11]:
c1 = np.array(c)
c1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
c1.ndim

2

In [13]:
c1.shape

(2, 4)

In [14]:
d = [[[3, 4, 5, 6],
      [7, 8, 9, 10]],
      
     [[21, 22, 23, 24],
      [25, 26, 27, 28]],
     
     [[50, 51, 52, 53],
      [54, 55, 56, 57]]]
type(d)

list

In [15]:
d1 = np.array(d)
d1

array([[[ 3,  4,  5,  6],
        [ 7,  8,  9, 10]],

       [[21, 22, 23, 24],
        [25, 26, 27, 28]],

       [[50, 51, 52, 53],
        [54, 55, 56, 57]]])

In [16]:

d1.ndim

3

In [17]:
d1.shape

(3, 2, 4)

In [18]:

g = [1, 2, 3, 4]
type(g)

list

In [19]:
g*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [20]:

g1 = []
for i in g:
    g1.append(i*3)

In [21]:
g

[1, 2, 3, 4]

In [23]:
g1

[3, 6, 9, 12]

In [24]:
h = np.array(g)
h

array([1, 2, 3, 4])

In [25]:
j = 3*h
j

array([ 3,  6,  9, 12])

In [26]:
k = 2.5*h
k

array([ 2.5,  5. ,  7.5, 10. ])

In [27]:
h**(1/2)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [29]:
a = [4, 5, 6, 7]
type(a)

list

In [30]:
p = 1
for i in a:
    p = p*i

In [31]:
p

840

In [32]:
a

[4, 5, 6, 7]

In [33]:
4*5*6*7

840

In [34]:

np.prod(a)

np.int64(840)

In [35]:

np.mean(a)

np.float64(5.5)

In [36]:
(4 + 5 + 6 + 7)/4

5.5

In [37]:

np.sum(a)

np.int64(22)

In [38]:
np.median(a)

np.float64(5.5)

In [39]:
np.std(a)

np.float64(1.118033988749895)

In [40]:
a

[4, 5, 6, 7]

In [41]:

np.min(a)

np.int64(4)

In [42]:
np.max(a)

np.int64(7)

In [43]:
b = [[3, 4, 5, 6],
     [7, 8, 9, 10],
     [23, 25, 45, 46]]

In [44]:
np.sum(b)

np.int64(191)

In [45]:

np.sum(b, axis=0)

array([33, 37, 59, 62])

In [46]:
np.sum(b, axis=1)

array([ 18,  34, 139])